title: Zain Zhenyuan Ruan
logo: http://zainryan.github.io/photo.JPG
description: "zainruan [at] csail [dot] mit [dot] edu<br><br><a href='https://scholar.google.com/citations?user=3aCDoAYAAAAJ&hl=en'>View My Google Scholar Profile</a>"
google_analytics:
theme: jekyll-theme-minimal
